src/main/php/lang/FunctionType.class.php, src/test/php/net/xp_framework/unittest/core/FunctionTypeTest.class.php
This PR enables the following:
```php
class Person extends \lang\Object {
private $name;
public function __construct($name) { $this->name= $name; }
public function name() { return $this->name; }
}
// [Timm, Test]
$names= Sequence::of(new Person('Timm'), new Person('Test'))
->map('Person::name')
->toArray()
;
```
Previously, you'd have to write:
```php
// [Timm, Test]
$names= Sequence::of(new Person('Timm'), new Person('Test'))
->map(function($person) { return $person->name(); })
->toArray()
;
```
*(Examples use the awesome [sequence library](https://github.com/xp-forge/sequence/))*
=> Be able to refer to instance methods via string

src/main/php/lang/FunctionType.class.php, src/test/php/net/xp_framework/unittest/core/FunctionTypeInvokeable.class.php, src/test/php/net/xp_framework/unittest/core/FunctionTypeTest.class.php
This pull request supports the [__invoke()](http://php.net/manual/en/language.oop5.magic.php#object.invoke) method for function types:
```php
class Test extends \lang\Object {
public function __invoke($arg) { return 'Test'; }
}
$inv= FunctionType::forName('function(var): var')->cast(new Test());
$result= $inv();   // 'Test'
```
=> Feature: Support invokeables

src/main/php/lang/XPClass.class.php, src/main/php/lang/reflect/ClassParser.class.php, src/test/php/net/xp_framework/unittest/annotations/ClassMemberParsingTest.class.php, src/test/php/net/xp_framework/unittest/reflection/TypeRefByLiteralLoadedOnDemand.class.php, src/test/php/net/xp_framework/unittest/reflection/TypeRefByNameLoadedOnDemand.class.php, src/test/php/net/xp_framework/unittest/reflection/TypeTest.class.php, src/test/php/net/xp_framework/unittest/reflection/XPClassTest.class.php
This pull request adds support for `::class` notation in annotations and changes `lang.XPClass::forName()` to be able to accept these.
```php
#[@test, @expect(IllegalArgumentException::class)]
public function unhandled() {
...
}
```
See https://wiki.php.net/rfc/class_name_scalars (added in PHP 5.5)
=> Support class literals

.travis.yml, README.md, src/main/php/lang.base.php, src/main/php/lang/ClassLoader.class.php, src/test/php/net/xp_framework/unittest/core/ListOf.class.php, src/test/php/net/xp_framework/unittest/core/Named.class.php, src/test/php/net/xp_framework/unittest/core/NewInstanceTest.class.php
This pull request adds support for creating anonymous classes from traits.
Using this trait:
```php
trait Named {
private $name;
/** @return string */
public function name() { return $this->name; }
}
```
The call here:
```php
$named= newinstance('Named', ['Test'], [
'__construct' => function($name) { $this->name= $name; }
]);
```
Generates code equivalent to:
```php
class Named·1 extends \lang\Object {
use Named;
public function __construct($name) { $this->name= $name; }
}
```
Finally, calling the trait method will yield:
```php
$named->name();  // "Test"
```
=> Feature: Newinstance with traits

ChangeLog.md, src/main/php/lang/reflect/ClassParser.class.php, src/main/php/lang/reflect/Field.class.php, src/test/php/net/xp_framework/unittest/reflection/FieldsTest.class.php, src/test/php/net/xp_framework/unittest/reflection/TestClass.class.php
The reflection API now honors the `@var` apidoc tag.
```php
class Example extends \lang\Object {
/** @var string */
protected $description;
}
```
See http://www.phpdoc.org/docs/latest/references/phpdoc/tags/var.html
=> Feature: Field types via "var" tag.

src/main/php/lang.base.php, src/main/php/lang/ClassLoader.class.php, src/main/php/lang/Process.class.php, src/main/php/lang/Wildcard.class.php, src/main/php/lang/XPClass.class.php, src/main/php/unittest/TestResult.class.php, src/main/php/unittest/web/WebTestCase.class.php, src/main/php/util/CompositeProperties.class.php, src/main/php/util/Filters.class.php, src/main/php/util/cmd/Console.class.php, src/test/php/net/xp_framework/unittest/core/CastingTest.class.php, src/test/php/net/xp_framework/unittest/core/CloningTest.class.php, src/test/php/net/xp_framework/unittest/core/IsTest.class.php, src/test/php/net/xp_framework/unittest/core/NullTest.class.php, src/test/php/net/xp_framework/unittest/core/RuntimeInstantiationTest.class.php, src/test/php/net/xp_framework/unittest/core/StringOfTest.class.php, src/test/php/net/xp_framework/unittest/core/XpTest.class.php, src/test/php/net/xp_framework/unittest/reflection/ClassCastingTest.class.php, src/test/php/net/xp_framework/unittest/reflection/ClassLoaderTest.class.php, src/test/php/net/xp_framework/unittest/tests/AssertionsTest.class.php, src/test/php/net/xp_framework/unittest/util/FiltersTest.class.php, src/test/php/net/xp_framework/unittest/util/cmd/ConsoleTest.class.php
This pull request deprecates `xp::null()` and rewrites the code base to do without it.
Notable BC breaks:
* The call `XPClass::forName($name)->cast(null)` returns `null` now, and no longer the null-safe null. This way it's consistent with e.g. `Primitive::cast()` though. If you want null-safe casts, use the global `cast($expr, $type)` function.
* The class loading APIs will return `null` from their find*() methods now. To check, you need to use `null === $result` instead of `$result instanceof null`, which I couldn't find anywhere in the codebase or any project.
See https://github.com/xp-framework/rfc/issues/298
=> Deprecate null

src/main/php/xp/unittest/DefaultListener.class.php, src/test/php/net/xp_framework/unittest/tests/UnittestRunnerTest.class.php
Use ✓ and ✗ for success and failure if in terminal color mode. See feature request #55 
*Note: This will break cases when the unittest command was used in conjuction with `|grep "OK"`. Don't do this! - use the exit code instead.*
=> Feature: Unicode unittest icons

src/main/php/lang.base.php, src/main/php/lang/Throwable.class.php, src/main/php/lang/XPClass.class.php
This way, we don't execute it for every subclass of Throwable, which there are quite a bit of.
This PR has been backported to XP 5, see xp-framework/xp-framework#377
=> Move static initializer from Throwable -> XPClass

src/main/php/io/streams/LinesIn.class.php, src/main/php/io/streams/Reader.class.php, src/main/php/io/streams/TextReader.class.php, src/main/php/io/streams/TextWriter.class.php, src/test/config/unittest/io.ini, src/test/php/net/xp_framework/unittest/io/streams/LinesInTest.class.php, src/test/php/net/xp_framework/unittest/io/streams/TextReaderTest.class.php, src/test/php/net/xp_framework/unittest/io/streams/TextWriterTest.class.php
This pull request adds a new class `LinesIn` and a new method `TextReader::lines()` returning instanced of this class. With it the lines of the underlying stream can be iterated. Think of PHP's `file()` function but without first having to read the entire file into memory (plus, it works on any stream):
```php
use io\streams\TextReader;
$socket= ...;
$reader= new TextReader($socket);
foreach ($reader->lines() as $line) {
// Process
}
```
Combining this with the great [Sequence](https://github.com/xp-forge/sequence) library would make the following possible:
```php
use io\File;
use io\streams\LinesIn;
use util\data\Sequence;
use util\data\Collectors;
use text\regex\Scanner;
class Seq extends \lang\Object {
public static function main($args) {
$map= Sequence::of(new …
```
=> Text reader iteration

src/main/php/io/ZipFile.class.php
This PR suggests to deprecate the `io.ZipFile` class. Its name may suggest functionality like the [io.archive.zip library](https://github.com/xp-framework/zip), which it doesn't support - instead, it reads GZIP compressed data:
```sh
$ xp -w '$f= new \io\ZipFile("file.gz"); $f->open(FILE_MODE_READ); var_dump($f->read());'
io.ZipFile(uri= C:\cygwin\home\Timm\devel\xp\core\file.gz, mode= rb)
```
This can also be done by using the `GzDecompressingInputStream` class though. It's also not limited to files, but wraps any other input stream.
```sh
$ xp -w '(new \io\streams\GzDecompressingInputStream((new \io\File("file.gz"))->in()))->read()'
Hello World
```
=> Deprecate io.ZipFile

src/main/php/io/EncapsedStream.class.php, src/main/php/io/File.class.php, src/main/php/io/FileUtil.class.php, src/main/php/io/SpoolDirectory.class.php, src/main/php/io/TempFile.class.php, src/main/php/io/ZipFile.class.php, src/main/php/io/package-info.xp, src/main/php/io/streams/FileInputStream.class.php, src/main/php/io/streams/FileOutputStream.class.php, src/main/php/lang/ResourceProvider.class.php, src/main/php/lang/archive/Archive.class.php, src/main/php/security/Policy.class.php, src/main/php/security/auth/HtpasswdAuthenticator.class.php, src/main/php/util/Properties.class.php, src/main/php/util/cmd/SingleProcess.class.php, src/main/php/xp/xar/instruction/DiffInstruction.class.php, src/test/php/net/xp_framework/unittest/io/EncapsedStreamTest.class.php, src/test/php/net/xp_framework/unittest/io/FileIntegrationTest.class.php, src/test/php/net/xp_framework/unittest/reflection/ResourcesTest.class.php
This pull request adds class constants instead of the global `FILE_MODE_*` constants. To adopt your code, replace "FILE_MODE_" by the string "File::" as seen in this PR's diffs.
```php
$f= new File('tests');
$f->open(File::READ);  // Instead of $f->open(FILE_MODE_READ);
...
$f->close();
```
=> Introduce File mode constants

src/main/php/io/collections/ArchiveCollection.class.php, src/main/php/io/collections/ArchiveElement.class.php, src/main/php/lang/archive/Archive.class.php, src/main/php/xp/xar/instruction/CreateInstruction.class.php, src/main/php/xp/xar/instruction/DiffInstruction.class.php, src/main/php/xp/xar/instruction/ExtractInstruction.class.php, src/main/php/xp/xar/instruction/MergeInstruction.class.php, src/main/php/xp/xar/instruction/ShowInstruction.class.php, src/test/php/net/xp_framework/unittest/archive/ArchiveTest.class.php, src/test/php/net/xp_framework/unittest/archive/ArchiveV2Test.class.php, src/test/php/net/xp_framework/unittest/io/collections/ArchiveCollectionTest.class.php, src/test/php/net/xp_framework/unittest/reflection/ClassFromArchiveTest.class.php
Like #79, this PR introduces Archive class constants and deprecates the global ARCHIVE_* constants.
=> Introduce Archive constants

src/main/php/io/Folder.class.php, src/main/php/io/FolderEntries.class.php, src/main/php/io/Path.class.php, src/main/php/io/package-info.xp, src/test/config/unittest/io.ini, src/test/php/net/xp_framework/unittest/io/FolderEntriesTest.class.php, src/test/php/net/xp_framework/unittest/io/FolderTest.class.php
This PR adds a new method `entries()` to the io.Folder class and deprecates the iteration via `getEntry()`.
```php
$folder= new Folder('.');
while (false !== ($entry= $folder->getEntry())) {
$path= new Path($folder, $entry);
// ...
}
$path= new Path($folder, 'test.txt');
```
```php
$folder= new Folder('.');
foreach ($folder->entries() as $path) {
// ...
}
$path= $folder->entries()->named('test.txt');
```
=> Feature: Folder entries

src/main/php/io/Path.class.php, src/test/php/net/xp_framework/unittest/io/PathTest.class.php
This pull request removes the necessity of using conditionals in the following two usecases:
```php
$path= new Path('test.txt');
// Usecase 1: Also work for non-existant paths, e.g. because we want to write to the file
if ($path->exists()) {
$file= $path->asFile();
} else {
$file= new File($path);
}
$file->open(File::WRITE);
// Usecase 2: Ensure file exists, e.g. because we want to read from it
if ($path->exists()) {
$file= $path->asFile()->open(File::READ);
} else {
throw new IllegalStateException('File '.$path.' does not exist');
}
```
```php
$path= new Path('test.txt');
$file= $path->asFile()->open(File::WRITE);                // Usecase #1
$file= $path->asFile(Path::EXISTING)->open(File::READ);   // Usecase #2
```
*Note: The fluent API for File::open was introduced in …
=> Path::asFile() and asFolder() accept arguments

src/main/php/io/Path.class.php, src/main/php/xp/xar/instruction/CreateInstruction.class.php, src/test/php/net/xp_framework/unittest/io/PathTest.class.php
This pull request adds a static method `real()` to the io.Path class. With it, one can create instances which are resolved according to [realpath](http://php.net/realpath) semantics.
```php
// Before
$real= new Path(realpath($in));          // Does not work if $in does not exist
$real= (new Path($in))->asRealpath();    // Kind of long
// After
$real= Path::real($in);
```
Easiest way to fully qualify current directory now:
```sh
$ xp -w '\io\Path::real(".")'
C:\cygwin\home\Timm\devel\xp\core
```
=> Path::real()

src/main/php/lang.base.php, src/main/php/lang/Type.class.php, src/main/php/lang/TypeUnion.class.php, src/test/config/unittest/core.ini, src/test/php/net/xp_framework/unittest/core/IsTest.class.php, src/test/php/net/xp_framework/unittest/core/TypeUnionTest.class.php
Part of xp-framework/rfc#298
```php
$union= TypeUnion::forName('int|string');
$union->isInstance(1);        // TRUE
$union->isInstance('Hello');  // TRUE
$union->isInstance($this);    // FALSE
```
http://www.phpdoc.org/docs/latest/guides/types.html#multiple-types-combined
=> Implement TypeUnion type

src/main/php/lang.base.php, src/main/php/lang/Value.class.php, src/main/php/lang/types/ArrayList.class.php, src/main/php/lang/types/ArrayMap.class.php, src/main/php/unittest/ComparisonFailedMessage.class.php, src/main/php/util/Objects.class.php, src/main/php/util/collections/Arrays.class.php, src/main/php/util/collections/HashSet.class.php, src/main/php/util/collections/HashTable.class.php, src/main/php/util/collections/LRUBuffer.class.php, src/main/php/util/collections/Pair.class.php, src/main/php/util/collections/Queue.class.php, src/main/php/util/collections/Stack.class.php, src/main/php/util/collections/Vector.class.php, src/test/php/net/xp_framework/unittest/Name.class.php, src/test/php/net/xp_framework/unittest/core/StringOfTest.class.php, src/test/php/net/xp_framework/unittest/core/types/ArrayListTest.class.php, src/test/php/net/xp_framework/unittest/core/types/ArrayMapTest.class.php, src/test/php/net/xp_framework/unittest/tests/AssertionsTest.class.php, src/test/php/net/xp_framework/unittest/tests/Name.class.php, src/test/php/net/xp_framework/unittest/util/ObjectsTest.class.php
This PR implements xp-framework/rfc#297 and adds a `lang.Value` interface. This serves as a forward compatibility measure for the time when we no longer have a single `lang.Generic` root interface.
Classes which aren't value objects won't inherit the `lang.Object` class anymore in the future:
```php
class Program {
public static function main($args) {
Console::writeLine('Hello World');
}
}
```
Classes which should be comparable or usable as hash keys can choose to implement `lang.Value`:
```php
class Name implements \lang\Value {
private $value;
public function __construct($value) {
$this->value= (string)$value;
}
public function value() {
return $this->value;
}
public function compareTo($cmp) {
return $cmp instanceof self ? strcmp($this->value, $cmp->value) : -1;
} …
```
=> Value interface

src/main/php/lang.base.php, src/test/php/net/xp_framework/unittest/core/NullTest.class.php, src/test/php/net/xp_framework/unittest/core/XpTest.class.php
Restores PHP7 FC
```sh
$ XP_RT=7.0 xp -v
Fatal error: Cannot use 'null' as class name as it is reserved in 
C:\...\core\src\main\php\lang.base.php on line 288
```
=> Rename deprecated, non-public null class to `__null`

ChangeLog.md, src/main/php/io/EncapsedStream.class.php, src/main/php/lang.base.php, src/main/php/lang/FunctionType.class.php, src/main/php/util/PropertyExpansion.class.php
Related to pre-namespace class loading, lazily loads exception and then throws it. No longer necessary now that we are using the PHP builtin class loading, which is lazy by default
Part of 6.4.0-RELEASE per xp-framework/rfc#298
=> Remove deprecated raise() core functionality

ChangeLog.md, src/main/php/lang.base.php, src/main/php/peer/net/Inet6Address.class.php, src/main/php/xp/install/GitHubArchive.class.php, src/test/php/net/xp_framework/unittest/core/ThisTest.class.php
This pull request deprecates the `this()` core functionality. PHP 5.4, which we depend on since XP 6, has syntax for this:
```php
// PHP 5.3
$values= $response->header('Location');
$url= $values[0];
// PHP 5.3 with XP Framework
$url= this($response->header('Location'), 0);
// PHP 5.4+
$url= $response->header('Location')[0];
```
See https://wiki.php.net/rfc/functionarraydereferencing
Part of xp-framework/rfc#298
=> Deprecate this()

ChangeLog.md, src/main/php/xp/runtime/Code.class.php, src/main/php/xp/runtime/Dump.class.php, src/main/php/xp/runtime/Evaluate.class.php, src/test/config/unittest/core.ini, src/test/php/net/xp_framework/unittest/core/CodeTest.class.php
This pull request enables the easy use of `use` statements in the command line.
```sh
$ xp -w 'use lang\{Type, Object}; Type::forName(nameof(new Object()))'
lang.XPClass<lang.Object>
```
* A single statement, such as `use T;`
* Multiple statements, such as `use T1; use T2;`
* The combined `use T1, T2` syntax
* PHP7's [grouped syntax](https://wiki.php.net/rfc/group_use_declarations) `use ns\{T1, T2};` - *regardless of the PHP version!*
This pull request also adds consistency to `xp -e` and `xp -w|-d`. Both now accept sourcecode with leading PHP open tags and behave in the same way for the given arguments.
=> Feature: Use "use" statements in commandline

.travis.yml, README.md, composer.json, src/main/php/lang.base.php, src/test/php/net/xp_framework/unittest/io/collections/ArchiveCollectionTest.class.php, src/test/php/net/xp_framework/unittest/io/streams/ChannelWrapper.class.php, src/test/php/net/xp_framework/unittest/reflection/PrimitiveAndWrappersTest.class.php, src/test/php/net/xp_framework/unittest/util/cmd/ConsoleTest.class.php
This pull request:
This is part of the road towards XP7 as per xp-framework/rfc#298
***Note:*** *Unofficially (meaning: tests will no longer verify its functionality), XP 6.5.0 will still run on PHP 5.4.X, as none of the code in src/main uses PHP 5.5 features yet! This is why the statement in [__xp.php](https://github.com/xp-framework/core/blob/v6.4.0/src/main/php/__xp.php) was deliberately left "inconsistent" with the version requirements stated in composer.json!*
=> Refactor: Use finally

src/main/php/lang/FunctionType.class.php, src/main/php/util/collections/HashSet.class.php, src/main/php/util/collections/HashTable.class.php, src/main/php/util/collections/LRUBuffer.class.php, src/main/php/util/collections/Queue.class.php, src/main/php/util/collections/Stack.class.php, src/main/php/util/collections/Vector.class.php, src/test/php/net/xp_framework/unittest/util/collections/HashSetTest.class.php, src/test/php/net/xp_framework/unittest/util/collections/HashTableTest.class.php, src/test/php/net/xp_framework/unittest/util/collections/LRUBufferTest.class.php, src/test/php/net/xp_framework/unittest/util/collections/QueueTest.class.php, src/test/php/net/xp_framework/unittest/util/collections/StackTest.class.php, src/test/php/net/xp_framework/unittest/util/collections/VectorTest.class.php
This pull request refactors the following:
```php
// Before
$h=  ($val instanceof Generic || $val instanceof Value) ? $val->hashCode() : serialize($val);
// After
$h= Objects::hashOf($val);
```
This has the benefit of not repeating ourselves and allows closures inside util.collections; they would previously raise a `cannot serialize instances of Closure` error!
=> Use Objects::hashOf() in collections

src/main/php/xp/runtime/Reflect.class.php, src/test/php/net/xp_framework/unittest/tests/ListenerTest.class.php
Shown as abstract classes
```sh
$ xp -r lang.partial
@FileSystemCL<...\xp\partial\src\main\php\>
@FileSystemCL<...\xp\partial\src\test\php\>
package lang.partial {
package lang.partial.unittest
public abstract class lang.partial.Identity
public abstract class lang.partial.InstanceCreation
public abstract class lang.partial.ListIndexedBy
public abstract class lang.partial.ListOf
public abstract class lang.partial.Transformation
public class lang.partial.Comparators
public class lang.partial.Comparison
public class lang.partial.Constructor
public class lang.partial.Sortable
public class lang.partial.ValueObject
public class lang.partial.WithCreation
}
```
Distinguishable by "trait" keyword, ordered after interfaces (if any)
```sh
$ xp -r lang.partial …
```
=> Show traits w/ trait keyword, w/o abstract modifiers

src/main/php/io/collections/ArchiveElement.class.php, src/main/php/io/collections/FileElement.class.php, src/test/php/net/xp_framework/unittest/io/collections/MockElement.class.php
=> Add in() and out() methods to replace get(Input|Output)Stream()

src/main/php/lang/ClassLoader.class.php, src/main/php/lang/FunctionType.class.php, src/main/php/lang/XPClass.class.php, src/main/php/lang/reflect/Parameter.class.php, src/test/php/net/xp_framework/unittest/reflection/MethodParametersTest.class.php
Supports both PHP 5.6 / HHVM dedicated syntax (with optional PHP 7 varargs typing via `T...`):
```php
public function format($str, ...$args) {
// ...
}
```
...as well as apidoc "typing" via `@param T...` which also works in PHP 5.4 and PHP 5.5 (*though note the optional value is necessary!*):
```php
/**
* @param  string $str
* @param  var... $args
*/
public function format($str, $args= null) {
$args= array_slice(func_get_args(), 1);
// ...
}
```
In both situations, `lang.reflect.Parameter::isVariadic()` will return true (as will `isOptional()`). The type of a variadic parameter is the simple type it's annotated with, e.g. `string... $args` will yield the **string** primitive.
Checks using `ReflectionParameter::isVariadic()` first. If this method is available (it's not in versions before …
=> Variadic parameter support in reflection

README.md, src/main/php/lang.base.php, src/main/php/lang/Object.class.php, src/main/php/lang/Throwable.class.php, src/main/php/lang/WildcardType.class.php, src/main/php/util/AbstractDeferredInvokationHandler.class.php, src/main/php/util/Objects.class.php, src/test/php/net/xp_framework/unittest/core/NewInstanceTest.class.php, src/test/php/net/xp_framework/unittest/core/TypeOfTest.class.php
This pull request adopts changes to make the framework work without `lang.Object`, and is a prerequisite for removing it as suggested in xp-framework/rfc#297
=> Go baseless

src/main/php/util/Objects.class.php, src/test/php/net/xp_framework/unittest/util/ObjectsTest.class.php
Now, the following yield the expected results:
```php
Objects::equal(new \ReflectionClass(self::class), new \ReflectionClass(self::class));   // true
Objects::compare(new \ReflectionClass(self::class), new \ReflectionClass(self::class)); // 0
```
Essentially, with this in place, `equal()` is the equivalent of `===` and `compare()` that of `<=>` but with the possibility to overload (via lang.Object::equals() / lang.Value::compareTo() for both cases).
Also, `hashOf()` was optimized to use spl_object_hash() instead of serialize() on objects, which gives a much shorter representation!
See https://github.com/xp-framework/unittest/issues/13
See https://wiki.php.net/rfc/combined-comparison-operator
See http://php.net/manual/en/language.oop5.object-comparison.php …
=> Extend util.Objects to handle instances of non-XP classes

src/main/php/lang/AbstractClassLoader.class.php
* Remove shortening paths by omitting path segments
* Instead, replace current directory with ".", home directory with "~" and the APPDATA special folder with $APPDATA (or %APPDATA% on Windows)
```sh
$ xp -m $APPDATA/Composer/vendor/xp-framework/unittest -v
XP 6.9.3-dev { PHP 7.0.0 & ZE 3.0.0 } @ Windows NT SLATE 10.0 build 10586 (Windows 10) i586 
Copyright (c) 2001-2016 the XP group
FileSystemCL<...\xp-framework\unittest\src\main\php\>
FileSystemCL<...\xp\core\src\main\php\>
FileSystemCL<...\xp\sequence\src\main\php\>
FileSystemCL<...\xp\sequence\src\test\php\>
FileSystemCL<...\xp\collections\src\main\php\>
FileSystemCL<...\xp\core\src\test\php\>
FileSystemCL<...\xp\core\src\main\resources\>
FileSystemCL<...\xp\core\src\test\resources\> …
```
=> Make paths displayed in toString() copy&pasteable

src/main/php/lang/AbstractClassLoader.class.php, src/main/php/lang/reflect/ClassParser.class.php, src/test/php/net/xp_framework/unittest/reflection/ClassDetailsTest.class.php, src/test/php/net/xp_framework/unittest/reflection/ClassLoaderTest.class.php
See xp-framework/unittest#17
```sh
friebe@wirearchy ~
$ cat Test.class.php
<?php
friebe@wirearchy ~
$ xp Test
Uncaught exception: Exception lang.ClassFormatException (Class "Test" not declared in loaded file)
at lang.AbstractClassLoader::loadClass0((0x4)'Test') [line 425 of ClassLoader.class.php]
at lang.ClassLoader::loadClass0((0x4)'Test') [line 529 of ClassLoader.class.php]
at lang.ClassLoader::loadClass((0x4)'Test') [line 346 of class-main.php]
friebe@wirearchy ~
$ xp Test
Uncaught exception: Exception lang.ClassFormatException (Loading `Test`: No types declared in C:\tools\cygwin\home\friebe\Test.class.php)
at lang.AbstractClassLoader::loadClass0((0x4)'Test') [line 425 of ClassLoader.class.php]
at lang.ClassLoader::loadClass0((0x4)'Test') [line 529 of ClassLoader.class.php]
at …
```
=> Improve error messages when file loaded fails to declare type

src/main/php/lang/Enum.class.php, src/main/php/lang/Type.class.php, src/main/php/lang/XPClass.class.php, src/main/php/lang/reflect/Field.class.php, src/main/php/lang/reflect/Parameter.class.php, src/main/php/lang/reflect/Routine.class.php, src/test/config/unittest/core.ini, src/test/php/net/xp_framework/unittest/reflection/HackLanguageEnum.class.php, src/test/php/net/xp_framework/unittest/reflection/HackLanguageSupport.class.php, src/test/php/net/xp_framework/unittest/reflection/HackLanguageSupportTest.class.php, src/test/php/net/xp_framework/unittest/reflection/MethodParametersTest.class.php
See https://github.com/xp-framework/rfc/issues/308
This pull request supersedes #57 and implements the following [Hack](http://hacklang.org/) features in XP:
Hack generics and attributes are not supported. See [this comment on #122](https://github.com/xp-framework/core/pull/122#issuecomment-174302371): We only cover the very basics to make reflection work consistently with PHP and Hack. Other features need to be implemented (or already are) in libraries such as https://github.com/xp-forge/mirrors!
Test.class.php:
```php
<?hh
class Test {
public static function main(array<string> $args): int {
Console::writeLine('Hello World');
return 0;
}
}
```
Load and run:
```sh
vagrant@vagrant-ubuntu-vivid-64:/devel/xp/core$ XP_RT=hhvm xp Test
Hello World
```
Reflect:
```sh …
```
=> Add basic hack language support

src/main/php/io/Path.class.php, src/main/php/io/streams/BufferedInputStream.class.php, src/main/php/io/streams/BufferedOutputStream.class.php, src/main/php/io/streams/Bz2CompressingOutputStream.class.php, src/main/php/io/streams/Bz2DecompressingInputStream.class.php, src/main/php/io/streams/ChannelInputStream.class.php, src/main/php/io/streams/ChannelOutputStream.class.php, src/main/php/io/streams/ConsoleInputStream.class.php, src/main/php/io/streams/ConsoleOutputStream.class.php, src/main/php/io/streams/DeflatingOutputStream.class.php, src/main/php/io/streams/FileInputStream.class.php, src/main/php/io/streams/FileOutputStream.class.php, src/main/php/io/streams/GzCompressingOutputStream.class.php, src/main/php/io/streams/GzDecompressingInputStream.class.php, src/main/php/io/streams/InflatingInputStream.class.php, src/main/php/io/streams/MemoryInputStream.class.php, src/main/php/io/streams/MemoryOutputStream.class.php, src/main/php/io/streams/Reader.class.php, src/main/php/io/streams/StreamTransfer.class.php, src/main/php/io/streams/Streams.class.php, src/main/php/io/streams/StringReader.class.php, src/main/php/io/streams/StringWriter.class.php, src/main/php/io/streams/Writer.class.php
See https://github.com/xp-framework/rfc/issues/297: This removes the `lang.Object` class as parent for all io.streams classes and the io.Path class.
=> Unbase streams

src/main/php/xp/runtime/Evaluate.class.php, src/main/resources/xp/runtime/eval.md, src/main/resources/xp/runtime/xp.md
Scripts do not have an enclosing class, but rather just start with the code right away (after some optional `use` statements). 
```php
<?php
use util\{Date, DateUtil};
$span= DateUtil::timespanBetween(new Date($argv[1]), Date::now());
Console::writeLine("Hey, you are ", $span->getDays(), " days old");
```
```sh
$ xp -e AgeInDays.script.php 1977-12-14
Hey, you are 13920 days old            
```
*This feature should also be backported to XP6*
=> Enable running scripts from files

src/main/php/xp/runtime/Version.class.php
Uses parse_ini_file() on the file /etc/os-release, described in http://0pointer.de/public/systemd-man/os-release.html
```sh
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"
```
See also http://0pointer.de/blog/projects/os-release.html and #131
=> OS Version handling for systems with /etc/os-release

src/main/php/peer/CryptoSocket.class.php, src/main/php/peer/SSLHandshakeException.class.php, src/main/php/peer/SSLSocket.class.php, src/main/php/peer/SSLUnverifiedPeerException.class.php, src/main/php/peer/TLSSocket.class.php
This way, SSL / TLS errors can be distinguished from connection failures
on the network layer.
Introduce SSLHandshakeException, SSLUnverifiedPeerException at this
point, so it becomes possible to specifically catch those later.
=> Backport separation of connect & enable crypto

src/main/php/lang/GenericTypes.class.php, src/test/php/net/xp_framework/unittest/core/generics/InstanceReflectionTest.class.php, src/test/php/net/xp_framework/unittest/core/generics/Lookup.class.php
This pull request implements support for generic fields - see #143 
```php
#[@generic(self= 'T')]
class Test {
#[@generic(var= 'T[]')]
public $list;
}
```
=> Generic fields

src/main/php/lang.base.php, src/main/php/util/Random.class.php, src/test/config/unittest/util.ini, src/test/php/net/xp_framework/unittest/util/RandomTest.class.php
Implements feature suggested in #142 - a RNG in the framework.
This RNG prefers secure pseudo-random sources:
* random_bytes() / random_int() (PHP 7)
* mcrypt_create_iv(..., MCRYPT_DEV_URANDOM) (ext/mcrypt)
* /dev/urandom (on Un*x based systems)
* openssl_random_pseudo_bytes() (ext/openssl)
...and degrades to using the Mersenne Twister algorithm (mt_rand())
```php
use util\Random;
$random= new Random();
$bytes= $random->bytes(20);  // util.Bytes instance with 20 random bytes
$one= $random->int();        // Between 0 and PHP_INT_MAX
$two= $random->int(5, 10);   // Between 5 and 10, inclusive
```
By default, the implementation will use secure pseudo-random sources. This can have the downside of being slow. If you don't care for cryptographically secure randoms, use the following:
```php …
```
=> Create util.Random class: A random number generator

.travis.yml, ChangeLog.md, src/main/php/lang/Runtime.class.php, src/main/php/lang/RuntimeOptions.class.php, src/test/php/net/xp_framework/unittest/core/RuntimeInstantiationTest.class.php, src/test/php/net/xp_framework/unittest/core/RuntimeOptionsTest.class.php
Passes arguments using binary-safe `utf-7` encoding - see [Command.cs from xp-runners/reference](https://github.com/xp-runners/reference/blob/847e89345b18585d733d61cecf95bc659f9861ec/src/xp.runner/Command.cs#L91) and [class-main.php from xp-runners/main](https://github.com/xp-runners/main/blob/2223c46ad462455615a60fd39e103af2af44bada/src/class-main.php#L88)
=> Fix passing unicode arguments via `Runtime::newInstance()`

src/main/php/lang/Type.class.php, src/test/php/net/xp_framework/unittest/reflection/TypeTest.class.php
This pull request adds `lang.Type::$ITERABLE` to represent the `iterable` type introduced in PHP 7.1 (see https://wiki.php.net/rfc/iterable). 
*Please note this pull request does not require PHP 7.1 as it does not use `is_iterable()` but reimplements it.*
=> Implement iterable type

src/main/php/lang/Environment.class.php, src/main/php/lang/System.class.php, src/test/config/unittest/core.ini, src/test/php/net/xp_framework/unittest/core/EnvironmentSet.class.php, src/test/php/net/xp_framework/unittest/core/EnvironmentTest.class.php
This pull request adds a new `lang.Environment` class with implements access to environment variables and settings depending on the environment in a OS-independent matter. Supports Cygwin on Windows and [XDG](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) on Unix.
```php
public abstract class lang.Environment {
public static [:string] variables(string|string[] $filter)
public static string variable(string|string[] $arg, var... $default)
public static void export([:string] $variables)
public static string tempDir()
public static string homeDir()
public static string configDir(string $named)
public static string trustedCertificates(string $default)
}
```
The `lang.System` class can now be considered deprecated. **It will be removed in XP 8.0.**
The …
=> Environment class

src/main/php/lang.base.php, src/main/php/lang/Type.class.php, src/test/php/net/xp_framework/unittest/core/IsTest.class.php, src/test/php/net/xp_framework/unittest/reflection/TypeTest.class.php
This pull request extends the XP Framework's type system to include `lang.Type::$OBJECT`. This type union represents any object: Those from the framework, foreign ones as well as PHP builtins, except closures.
| Instance | Represents |
|-------------------------- | ------------------------ |
| `lang.Type::$VAR`          | Any type |
| `lang.Type::$VOID`         | No type, see also https://wiki.php.net/rfc/void_return_type |
| `lang.Type::$ARRAY`        | Arrays type union - zero-based or key/value pairs |
| `lang.Type::$CALLABLE`     | See http://php.net/manual/en/language.types.callable.php |
| `lang.Type::$ITERABLE`     | See https://github.com/xp-framework/core/pull/154 |
| `lang.Primitive::$INT`     | integers |
| `lang.Primitive::$DOUBLE`  | floating point numbers |
| …
=> Implement object type union

src/main/php/util/Date.class.php, src/test/php/net/xp_framework/unittest/util/DateTest.class.php
* Removes legacy serialization (*has been deprecated since October 2011, see xp-framework/rfc#115*)
* Speeds up format() by replacing `preg_replace_callback` and helper method with `strtr`
* Uses new XP8 syntax (including [compact apidoc](https://github.com/xp-framework/rfc/issues/310#issuecomment-242978257))
=> Refactor date serialization

src/main/php/util/Properties.class.php, src/test/config/unittest/util.ini, src/test/php/net/xp_framework/unittest/util/AbstractPropertiesTest.class.php, src/test/php/net/xp_framework/unittest/util/CompositePropertiesTest.class.php, src/test/php/net/xp_framework/unittest/util/FileBasedPropertiesTest.class.php, src/test/php/net/xp_framework/unittest/util/PropertyManagerTest.class.php, src/test/php/net/xp_framework/unittest/util/StreamBasedPropertiesTest.class.php
=> Refactor Properties I/O

src/main/php/util/Properties.class.php, src/main/php/util/PropertyExpansion.class.php, src/main/php/util/RegisteredPropertySource.class.php, src/test/config/unittest/util.ini, src/test/php/net/xp_framework/unittest/util/AbstractPropertiesTest.class.php, src/test/php/net/xp_framework/unittest/util/PropertyExpansionTest.class.php
Instead of an optional expansion parameter to load() - which is usually not called directly but by means of lazy loading - add an expanding() instance method to util.Properties
```php
$prop= (new Properties('file.ini'))->expanding('credentials', function($name) {
// TBI ...
});
```
Will be released in 7.8.0 and then merged to XP8
=> Make adding property file expansions easy to use

src/main/php/io/streams/TextReader.class.php, src/test/php/net/xp_framework/unittest/io/streams/TextReaderTest.class.php
```php
<?php
use io\streams\TextReader;
use io\streams\FileInputStream;
use io\File;
class LineReading extends \util\profiling\Measurable {
const FIXTURE = 'certs.lst';
#[@measure]
public function readLine_old() {
$r= new TextReader(new FileInputStream(self::FIXTURE));
$lines= 0;
$longest= 0;
while (null !== ($line= $r->readLine_old())) {
$lines++;
$longest= max($longest, strlen($line));
}
return [$lines, $longest];
}
#[@measure]
public function readLine() {
$r= new TextReader(new FileInputStream(self::FIXTURE));
$lines= 0;
$longest= 0;
while (null !== ($line= $r->readLine())) {
$lines++;
$longest= max($longest, strlen($line));
}
return [$lines, $longest];
}
}
```
```bash
$ xp -m devel\xp\measure\ util.profiling.Measure LineReading  -n 10
readLine_old: 10 iteration(s), 3.195 seconds, …
```
=> Increase TextReader::readLine() performance 50-fold (!)

src/main/php/xp/xar/Runner.class.php, src/main/resources/xp/runtime/ar.md
Implements xp-runners/reference#67 by:
* Changing usage to use `xar` instead of `xp ar`
* Changing `xar` invoked w/o arguments to effectively run `xp help ar`.
=> Reinstate XAR command

src/main/php/io/streams/ConsoleInputStream.class.php, src/main/php/io/streams/ConsoleOutputStream.class.php, src/main/php/io/streams/InputStreamReader.class.php, src/main/php/io/streams/LinesIn.class.php, src/main/php/io/streams/OutputStream.class.php, src/main/php/io/streams/OutputStreamWriter.class.php, src/main/php/io/streams/Reader.class.php, src/main/php/io/streams/StringReader.class.php, src/main/php/io/streams/StringWriter.class.php, src/main/php/io/streams/TextReader.class.php, src/main/php/io/streams/TextWriter.class.php, src/main/php/io/streams/Writer.class.php, src/main/php/util/cmd/Console.class.php, src/main/php/util/cmd/NoConsole.class.php, src/main/php/util/cmd/NoInput.class.php, src/main/php/util/cmd/NoOutput.class.php, src/test/php/net/xp_framework/unittest/util/cmd/ConsoleTest.class.php
This pull request:
* Changes `io.streams.StringReader` and `io.streams.TextReader` to both inherit from `io.streams.Reader`. The first reads without encoding, the latter does.
* Does the same for `io.streams.StringWriter` and `io.streams.TextWriter`
* Deprecates `getStream()` in favor of `stream()` and `setStream()` in favor of `redirect()`.
In addition to cleaning up the odd API, util.cmd.Console becomes useable in place where previously only TextReaders were accepted, see for example xp-forge/markdown#11
Old readers:
```php
package io.streams;
public class StringReader extends Reader {
public __construct(InputStream $in)
public InputStream getStream()
public var setStream(InputStream $stream)
public string toString()
public string read(int $size)
public string readLine()
}
public class …
```
=> Clean up inheritance and implementation oddities in io.streams

src/main/php/lang/FunctionType.class.php, src/main/php/lang/XPClass.class.php, src/main/php/lang/reflect/Method.class.php, src/test/php/net/xp_framework/unittest/core/ReferencesTest.class.php, src/test/php/net/xp_framework/unittest/core/StringOfTest.class.php, src/test/php/net/xp_framework/unittest/reflection/AbstractTestClass.class.php, src/test/php/net/xp_framework/unittest/reflection/TestClass.class.php
Fixes the following:
```bash
$ xp -w 'cast("lang.XPClass::newInstance", "function(var): var")'
Uncaught exception: Exception lang.ClassCastException (Cannot cast)
Caused by Exception lang.ClassNotFoundException (Class "lang.Object" could not be found)
```
=> Remove all reference to lang.Object

src/main/php/io/sys/Ftok.class.php, src/main/php/io/sys/IPCMessage.class.php, src/main/php/io/sys/IPCQueue.class.php, src/main/php/io/sys/Semaphore.class.php, src/main/php/io/sys/ShmSegment.class.php
This RFC implements the first part of https://github.com/xp-framework/rfc/issues/329 and deprecates the `io.sys` package.
=> Deprecate io.sys package

src/main/php/util/DateUtil.class.php, src/test/php/net/xp_framework/unittest/util/DateUtilTest.class.php
These new methods work with `util.TimeSpan` instances:
```php
$date= Date::now();
$tomorrow= DateUtil::add($date, TimeSpan::days(1));
$yesterday= DateUtil::subtract($date, TimeSpan::days(1));
```
/cc @mikey179
=> Add DateUtil::add() and DateUtil::subtract()

src/main/php/io/Path.class.php, src/test/php/net/xp_framework/unittest/io/PathTest.class.php
Now handles the `.` directory as well as absolute Unix paths correctly.
| Input | Old  | New | Comment |
| ------ | ----- | ----- | ------------------------------------------------------------------------------ |
| "."      | ""     | "." | Kind of OK, since "" basically also means the current directory                    |
| "./."    | ""     | "." | -"- |
| "a/.."  | ""     | "." | -"- |
| "C:"    | "C:"  | "C:\\" | Windows drive root is now always returned with a trailing backslash |
| "C:\\"   | "C:"  | "C:\\" | -"- |
| "/"      | ""     | "/" | This is the real bug! |
| "/var" | "var" | "/var" | Obviously also broken |
=> Fix path normalization

.travis.yml, src/main/php/lang/Enum.class.php, src/main/php/util/Observable.class.php, src/main/php/util/Random.class.php, src/test/php/net/xp_framework/unittest/core/CommandLineTest.class.php, src/test/php/net/xp_framework/unittest/core/ExceptionsTest.class.php, src/test/php/net/xp_framework/unittest/core/RuntimeOptionsTest.class.php, src/test/php/net/xp_framework/unittest/core/RuntimeTest.class.php
See https://wiki.php.net/rfc/deprecations_php_7_4
=> PHP 7.4 forward compatiblity

src/main/php/lang/Process.class.php, src/test/php/net/xp_framework/unittest/core/ProcessTest.class.php
The `terminate()` method kills processes with a given signal; like PHP's [proc_terminate()](http://php.net/proc_terminate)
=> Implement Process::terminate()

src/main/php/xp/runtime/Code.class.php, src/main/php/xp/runtime/Dump.class.php, src/main/php/xp/runtime/Evaluate.class.php, src/main/php/xp/runtime/Script.class.php, src/test/php/net/xp_framework/unittest/runtime/CodeTest.class.php
This pull request ensures filenames and lines match up to parsed code for `xp eval/dump/write` and XP scripts. 
```php
<?php namespace test;
Console::writeLine('Hello ', $argv[1]); 
```
```sh
$ xp test.script.php
Uncaught exception: Exception lang.IndexOutOfBoundsException (Undefined offset: 1)
at <main>::__error(8, ...) [line 1 of Code.class.php(124) : eval()'d code]
at <main>::eval() [line 124 of Code.class.php]
at xp.runtime.Code::run(...) [line 29 of Evaluate.class.php]
at xp.runtime.Evaluate::main(array[1]) [line 374 of class-main.php]
$ echo 'throw new \Exception("Test")' | xp -e
Uncaught exception: Exception lang.XPException (Test)
at <native>::Exception(0, (0x4)'Test') [line 1 of Code.class.php(124) : eval()'d code]
at <main>::eval() [line 124 of …
```
=> Ensure filenames and lines match up to parsed code

src/main/php/lang.base.php, src/main/php/lang/XPClass.class.php, src/test/php/net/xp_framework/unittest/reflection/ClassDetailsTest.class.php
This removes `xp::$registry` which has since been replaced by dedicated functionality.
=> Remove deprecated XP registry

src/main/php/lang.base.php, src/main/php/lang/Primitive.class.php, src/main/php/lang/Type.class.php, src/test/php/net/xp_framework/unittest/core/XpTest.class.php, src/test/php/net/xp_framework/unittest/reflection/PrimitiveTest.class.php
We use `int` for integer numbers (and not *long*), so we should be using `float` for floating point numbers (and not *double*). The latter are implementation details, whereas *int* and *float* are generic terms.
See also https://wiki.php.net/rfc/var_type
=> Remove "double" type in favor of "float"

src/main/php/lang.base.php, src/test/php/net/xp_framework/unittest/core/CastingTest.class.php
Replaced by nullable types
See https://github.com/xp-framework/rfc/issues/326
=> Remove third & optional "nullsafe" argument to cast()

src/main/php/util/Dates.class.php, src/test/config/unittest/date.ini, src/test/php/net/xp_framework/unittest/util/DatesTest.class.php
```php
public class util.Dates {
public static util.Date add(util.Date $date, util.TimeSpan|int|string $span)
public static util.Date subtract(util.Date $date, util.TimeSpan|int|string $span)
public static util.Date truncate(util.Date $date, util.TimeInterval $interval)
public static util.Date ceiling(util.Date $date, util.TimeInterval $interval)
public static util.TimeSpan diff(util.Date $a, util.Date $b)
public static int compare(util.Date $a, util.Date $b)
}
```
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/DateUtils.html
=> Add new util.Dates class superseding util.DateUtil

ChangeLog.md, src/main/php/lang.base.php, src/main/php/lang/Type.class.php, src/test/php/net/xp_framework/unittest/core/IsTest.class.php, src/test/php/net/xp_framework/unittest/reflection/TypeTest.class.php
This pull request changes `is()` and `lang.Type::$OBJECT` to behave exactly like the PHP type hint *object*. Previously, it was inconsistent regarding closures and generators:
```php
function test(object $f) { return true; }
$f= function() { };
$result= test($f);          // true
$verify= is('object', $f);  // false ⚡️ 
```
See also xp-framework/compiler#68
=> Make object type consistent with PHP type system

src/main/php/lang.base.php, src/test/php/net/xp_framework/unittest/core/IsTest.class.php
This pull request adds support for nullable types to `is()` and makes is consistent with `cast()`.
```php
is('?int', null) // true
is('?int', 1)    // true
```
Previously, using nullable type notation would result in *lang.IllegalArgumentException (Not a wildcard type: ?int)*, so this is considered a bugfix.
=> Add support for nullable types to is()

src/main/php/lang.base.php, src/main/php/lang/AnonymousClassLoader.class.php, src/main/php/lang/XPClass.class.php, src/main/php/lang/reflect/ClassParser.class.php, src/test/php/net/xp_framework/unittest/core/AnnotationTest.class.php, src/test/php/net/xp_framework/unittest/reflection/ClassDetailsTest.class.php, src/test/php/net/xp_framework/unittest/reflection/ModuleLoadingTest.class.php, src/test/php/net/xp_framework/unittest/reflection/ProxyTest.class.php, src/test/php/net/xp_framework/unittest/reflection/XPClassTest.class.php
Example:
```php
$instance= new class() {
#[@test]
public function fixture() { }
};
$annotations= typeof($instance)->getMethod('fixture')->getAnnotations();
// ['test' => null]
```
=> Support getting annotations from anonymous classes

src/main/php/lang/reflect/ClassParser.class.php, src/test/php/net/xp_framework/unittest/reflection/ClassDetailsTest.class.php
Allows using `fn` inside annotations in addition to being able to use `function`.
```php
class RandomTest {
#[@test, @action(new VerifyThat(function() { return is_readable('/dev/urandom'); }))]
public function urandom_bytes() {
// ...
}
}
```
Now it's also possible to use the shorter and more concise form, even on PHP < 7.4!
```php
class RandomTest {
#[@test, @action(new VerifyThat(fn() => is_readable('/dev/urandom')))]
public function urandom_bytes() {
// ...
}
}
```
=> Add support for PHP 7.4 arrow functions in annotations

src/main/php/lang/Enum.class.php, src/test/php/net/xp_framework/unittest/core/EnumTest.class.php
Following the *be liberal in what you accept* principle:
```php
use my\enum\Name;
// Current functionality
$values= Enum::valuesOf(XPClass::forName(Name::class));
// Now also possible
$values= Enum::valuesOf(Name::class);
```
=> Allow passing string types to Enum::valueOf() / Enum::valuesOf()

src/main/php/lang/reflect/Package.class.php, src/test/php/net/xp_framework/unittest/reflection/PackageTest.class.php
```php
// Before, creates both XPClass *and* Package instances
$p= XPClass::forName(self::class)->getPackage();
// New light-weight functionality, only creates Package instance
$p= Package::of(self::class);
```
=> Add new method Package::of() which returns the package of a given type

.travis.yml
Released yesterday, see https://www.php.net/archive/2019.php#2019-11-28-1
=> Add PHP 7.4.0

ChangeLog.md, src/main/php/lang.base.php, src/main/php/lang/GenericTypes.class.php, src/main/php/lang/reflect/ClassParser.class.php, src/test/php/net/xp_framework/unittest/core/generics/AbstractDictionary.class.php, src/test/php/net/xp_framework/unittest/core/generics/GenericTypesTest.class.php, src/test/php/net/xp_framework/unittest/core/generics/ImplementationTest.class.php, src/test/php/net/xp_framework/unittest/core/generics/Marker.class.php, src/test/php/net/xp_framework/unittest/core/generics/TypeDictionary.class.php
Introduced in PHP 8.0, see https://wiki.php.net/rfc/namespaced_names_as_token
See also #211
=> Add handling for `T_NAME_FULLY_QUALIFIED` and `T_NAME_QUALIFIED` tokens

ChangeLog.md, src/main/php/lang.base.php, src/main/php/lang/reflect/ClassParser.class.php, src/test/php/net/xp_framework/unittest/reflection/ClassDetailsTest.class.php
Implements first step of xp-framework/rfc#336 by converting PHP 8 attributes into XP annotations: `#[Test(true)]` will beinterpreted the same as `#[@test(true)]`. This way, converting codebases over to the new syntax can start now. Another step to adopting PHP 8 - see #211
* * * 
Simple annotations must be rewritten as follows:
```diff
-  #[@test]
+  #[Test]
```
Annotations with named arguments can (*but do not have to*) be rewritten using named arguments:
```diff
-  #[@expect(['class' => IllegalStateException::class])]
+  #[Expect(class: IllegalStateException::class)]
```
Multiline annotations need to be folded:
```diff
-  #[@test, @values([
-  #  [0, []],
-  #  [1, [1]],
-  #  [4, [1, 2, 3, 4]]
-  #])]
+  #[Test, Values([[0, []], [1, [1]], [4, [1, 2, 3, 4]]])]
```
Annotations with …
=> Convert PHP 8 type, method and field attributes into XP annotations

ChangeLog.md, src/main/php/lang/Type.class.php, src/main/php/lang/reflect/Field.class.php, src/main/php/lang/reflect/Parameter.class.php, src/main/php/lang/reflect/Routine.class.php, src/test/php/net/xp_framework/unittest/reflection/FieldTypeTest.class.php, src/test/php/net/xp_framework/unittest/reflection/MethodParametersTest.class.php, src/test/php/net/xp_framework/unittest/reflection/MethodReturnTypesTest.class.php
This enables us to correctly resolve types such as `array<self>` for fields, method parameter and return types.
Before:
```bash
$ xp test src/test/config/unittest/reflect.ini
♥: 1035/1056 run (21 skipped), 1035 succeeded, 0 failed
Memory used: 7330.53 kB (7388.80 kB peak)
Time taken: 0.156 seconds
```
After:
```bash
$ xp test src/test/config/unittest/reflect.ini
♥: 1043/1064 run (21 skipped), 1043 succeeded, 0 failed
Memory used: 7411.90 kB (7470.16 kB peak)
Time taken: 0.143 seconds
```
=> Add Type::resolve()

src/main/php/lang/reflect/Parameter.class.php, src/test/php/net/xp_framework/unittest/reflection/MethodParametersTest.class.php
See https://github.com/xp-framework/compiler/pull/104#issuecomment-791924395, empowers the following when using the XP Compiler:
```php
#[Test]
public function parameter_default_reflective_access() {
$r= $this->run('use lang\ast\unittest\emit\Handle; class <T> {
public function run($h= new Handle(0)) {
return typeof($this)->getMethod("run")->getParameter(0)->getDefaultValue();
}
}');
Assert::equals(new Handle(0), $r);
}
```
=> Support reflective access to non-constant expressions for parameter defaults

.github/workflows/ci.yml, src/main/php/lang/Environment.class.php, src/test/php/net/xp_framework/unittest/core/EnvironmentSet.class.php, src/test/php/net/xp_framework/unittest/core/EnvironmentTest.class.php
The $_ENV global is only populated if the php.ini setting variables_order contains an "E", while $_SERVER always contains the environment variables. php.ini from the PHP GIT repo contains this:
```ini
; variables_order
;   Default Value: "EGPCS"
;   Development Value: "GPCS"
;   Production Value: "GPCS"
```
On Ubuntu, it's explicitely set as follows: `/etc/php/7.4/cli/php.ini:variables_order = "GPCS"`
See issue #265
=> Replace $_ENV with $_SERVER

src/main/php/lang/Type.class.php, src/main/php/lang/reflect/Routine.class.php, src/test/php/net/xp_framework/unittest/reflection/MethodReturnTypesTest.class.php
Forward compatible but also supports apidoc / syntax combination:
```php
/** @return never */
public function halt(): void { exit(); }
```
The reflection API lets apidoc take precedence over the `void` return type declared syntactically, as is done for e.g. callable and arrays
See https://wiki.php.net/rfc/noreturn_type. Implements runtime support for xp-framework/compiler#109
=> Support PHP 8.1 `never` type in reflection

src/main/php/util/Properties.class.php, src/test/php/net/xp_framework/unittest/util/PropertyExpansionTest.class.php
When working with injection files used in web applications outside of these applications, a property expansion named *app* needs to be registered for them to parse, even when values are not accessed!
An example is the following *inject.ini*:
```ini
string[sessions]=${app.tempdir}
```
To read these files, the following code is necessary:
```php
$config= (new Properties('inject.ini'))->expanding('app', fn($n) => '*'));
```
This pull request adds the ability to ignore any expansions as follows:
```php
$config= (new Properties('inject.ini'))->expanding('app', null);
```
=> Pass NULL to Properties::expanding() to ignore expansion

src/main/php/lang/AbstractClassLoader.class.php, src/main/php/lang/Environment.class.php, src/test/php/net/xp_framework/unittest/core/EnvironmentTest.class.php
The `platform()` method detects the current platform and is comparable with the PHP constant [PHP_OS_FAMILY](https://github.com/php/php-src/blob/7db146eea70e4c96ab57ca005f7e499884c14ecb/main/php.h#L39) - however, it recognizes Cygwin and also works for PHP 7.0 and PHP 7.1, where this constant is not yet defined.
```bash
$ xp -w '\lang\Environment::platform()'
Cygwin
```
Values returned can be one of:
* Windows
* Linux
* Darwin
* BSD
* Solaris
* Cygwin
* Unknown
* * * 
The `path()` method formats a path to a short format usable in the given platform, e.g. using ".", ".." and "~" to reference the current, parent and home directories, as well as $USERPOFILE and $APPDATA on Windows
```bash
$ xp -w '\lang\Environment::path()'
.
$ xp -w '\lang\Environment::path(getenv("HOME"))'
~
$ xp -w …
```
=> Add Environment::platform() and Environment::path()

src/main/php/lang/Process.class.php
The `wmic` tool lets us run Windows Management queries without `com_dotnet` enabled, fixing ugly *Cannot find executable: Class "Com" not found* errors when using `lang.Process::getProcessById()`.
We've now reduced the dependencies for running XP core even further:
```bash
$ grep -Hrn 'new \\Com' src/main/php/
src/main/php/lang/Process.class.php:183:        $c= new \Com('winmgmts://./root/cimv2');
```
The fallback is slightly slower.
With `com_dotnet` extension loaded:
```bash
$ xp test src/test/php/net/xp_framework/unittest/core/ProcessTest.class.php
Time taken: 0.897 seconds
```
Without:
```bash
$ xp test src/test/php/net/xp_framework/unittest/core/ProcessTest.class.php
Time taken: 1.384 seconds
```
=> Fall back to wmic command line tool if com_dotnet extension is not loaded

src/main/php/lang.base.php, src/main/php/lang/Type.class.php, src/main/php/lang/TypeIntersection.class.php, src/main/php/lang/reflect/Field.class.php, src/main/php/lang/reflect/Parameter.class.php, src/main/php/lang/reflect/Routine.class.php, src/test/config/unittest/core.ini, src/test/php/net/xp_framework/unittest/core/IsTest.class.php, src/test/php/net/xp_framework/unittest/core/TypeIntersectionTest.class.php
```php
function fixture(Countable&Traversable $t) { ... }
```
See https://wiki.php.net/rfc/pure-intersection-types
=> Add support for PHP 8.1 intersection types

src/main/php/lang.base.php, src/main/php/lang/reflect/Field.class.php, src/main/php/lang/reflect/Modifiers.class.php, src/test/php/net/xp_framework/unittest/reflection/FieldAccessTest.class.php, src/test/php/net/xp_framework/unittest/reflection/FieldModifiersTest.class.php, src/test/php/net/xp_framework/unittest/reflection/ModifiersTest.class.php
This pull request implements support PHP 8.1 readonly properties as defined in https://wiki.php.net/rfc/readonly_properties_v2
```php
class Test {
public function __construct(public readonly int $prop = 0) { }
}
$test= new Test(6100);
$test->prop; // 6100
$test->prop= 6101; // Raises error
```
=> Add support for PHP 8.1 readonly properties

src/main/php/lang/CommandLine.class.php, src/main/php/lang/Process.class.php
This pull request adds a new method `resolve()` to the `lang.CommandLine` class which finds executables in the system path. This method supersedes `lang.Process::resolve()` which is therefore deprecated.
```bash
$ xp -w '[...lang\CommandLine::forName(PHP_OS)->resolve("curl")]'
["C:\Tools\Cygwin\bin\curl.exe", "C:\Windows\System32\curl.exe"]
$ xp -w '[...lang\CommandLine::forName(PHP_OS)->resolve("which")]'
["/usr/bin/which", "/bin/which"]
```
* If the given name does not contain a ".", try `[name].exe` and `[name].com` for both of the following
* If the given argument contains a "\\" or "/", check whether a file by the given name exists
* Otherwise, iterate over paths in %PATH% and check for qualified file names
*Note: If you want to execute .bat files, you need to use `cmd /c [file].bat` …
=> Add CommandLine::resolve()

src/main/php/lang/Process.class.php, src/test/php/net/xp_framework/unittest/core/ProcessTest.class.php
Supports the argument types listed under https://www.php.net/manual/en/function.proc-open.php
Allows redirection to another descriptor and/or the NUL device:
```php
// cmd 2>&1
new Process('cmd', [], null, null, [2 => ['redirect', 1]]);
// cmd 2>NUL or cmd 2>/dev/null, depending on platform
new Process('cmd', [], null, null, [2 => ['null']]);
```
*Supported natively by PHP 7.4 (see php/php-src@6285bb52faf407b07e71497723d13a1b08821352), simulated for lower PHP versions*
By inheriting the handles for standard input, output and error, we can simulate the [passthru()](https://www.php.net/passthru) function:
```php
$p= new Process('cmd', [], null, null, [STDIN, STDOUT, STDERR]);
$p->close();
```
*No polling is needed, `close()` will wait for the command to finish*.
=> Allow overwriting descriptors passed to proc_open()

src/main/php/lang/XPClass.class.php, src/main/php/lang/reflect/ClassParser.class.php, src/test/php/net/xp_framework/unittest/annotations/BrokenAnnotationTest.class.php, src/test/php/net/xp_framework/unittest/reflection/ClassDetailsTest.class.php
E.g. `[#\unittest\annotations\Test]` or `[#annotations\Test]`. Includes consistent namespace and imports resolution which did not take annotation names into consideration, and handling of trailing commas inside grouped annotations.
=> Fix qualified annotation names

src/main/php/io/streams/BufferedInputStream.class.php, src/main/php/io/streams/BufferedOutputStream.class.php, src/main/php/io/streams/Bz2CompressingOutputStream.class.php, src/main/php/io/streams/Bz2DecompressingInputStream.class.php, src/main/php/io/streams/ChannelInputStream.class.php, src/main/php/io/streams/ChannelOutputStream.class.php, src/main/php/io/streams/ConsoleInputStream.class.php, src/main/php/io/streams/ConsoleOutputStream.class.php, src/main/php/io/streams/DeflatingOutputStream.class.php, src/main/php/io/streams/FileInputStream.class.php, src/main/php/io/streams/FileOutputStream.class.php, src/main/php/io/streams/GzCompressingOutputStream.class.php, src/main/php/io/streams/GzDecompressingInputStream.class.php, src/main/php/io/streams/InflatingInputStream.class.php, src/main/php/io/streams/MemoryInputStream.class.php, src/main/php/io/streams/MemoryOutputStream.class.php, src/test/php/net/xp_framework/unittest/io/streams/ChannelStreamTest.class.php
See issue #310
```bash
$ xp -w 'new \io\streams\FileOutputStream("composer.json")'
io.streams.FileOutputStream {
*file => io.File(uri= C:\...\core\composer.json, mode= wb)
}
```
```bash
$ xp -w 'new \io\streams\FileOutputStream("composer.json")'
io.streams.FileOutputStream<io.File(uri= C:\...\core\composer.json, mode= wb)>
```
=> Make all InputStream & OutputStream implementations implement Value

src/main/php/util/Properties.class.php, src/main/php/util/PropertyExpansion.class.php, src/test/php/net/xp_framework/unittest/util/AbstractPropertiesTest.class.php
This PR prevents invoking toString() on `util.Properties` instances from including potentially secret values, see https://github.com/xp-framework/core/issues/312#issuecomment-1217969070. Also, the class now implements `lang.Value` so its `toString()` method will be correctly called from e.g. `util.Objects::stringOf()`.
```bash
$ cat > test.ini
[global]
db.pass={$env.DB_PASS}
$ export DB_PASS=secret!
$ xp -w '$p= new \util\Properties("test.ini"); $p->reset(); return $p->toString()'
util.Properties(test.ini)@{[global => [db.pass => "secret!"]]}
```
```bash
$ xp -w '$p= new \util\Properties("test.ini"); $p->reset(); return $p->toString()'
util.Properties(test.ini)@{[global => [db.pass => "${env.DB_PASS}"]]}
```
=> Delay expansion of values in property files until values are read

src/main/php/lang/Type.class.php, src/test/php/net/xp_framework/unittest/core/TypeResolveTest.class.php, src/test/php/net/xp_framework/unittest/reflection/TypeSyntaxTest.class.php
This PR makes `Type::named()` behave consistently with reflection for [nullable union types](https://wiki.php.net/rfc/union_types_v2#nullable_union_types).
```php
interface T { public function fixture(): int|string|null; }
$t= (new XPClass(T::class))->getMethod('fixture')->getReturnType();
// Yields: lang.Nullable<?string|int>
```
```php
$t= Type::named('int|string|null', []);
// Before: lang.TypeUnion<int|string|void>
// After:  lang.Nullable<?int|string>
```
=> Make Type::named() consistent with reflection for nullable union types

src/main/php/util/TimeZone.class.php, src/test/php/net/xp_framework/unittest/util/TimeZoneTest.class.php
The `util.TimeZone::hasDst()` method was broken in multiple ways:
* First of all, it was always returning *true* - `timezone_transitions_get()` always returns at least one element
* Second, whether or not a timezone has daylight savings time depends on the year
* Third, odd situations like [Berlin, 1945](https://www.timeanddate.de/stadt/zeitumstellung/deutschland/berlin?year=1945) were not handled at all
=> Fix util.TimeZone::hasDst()

src/main/php/lang.base.php, src/main/php/util/Date.class.php, src/test/php/net/xp_framework/unittest/core/BootstrapTest.class.php
Currently, the XP Framework checks whether `date.timezone` is configured properly to ensure all the date functionality works as expected; and raises an exception during bootstrapping if not. This prevents any XP core functionality, even those not reliant on dates, from working if no timezone is set. This pull request moves the check to the static initializer for `util.Date`.
/cc @mikey179
=> Defer `date.timezone` checks until the util.Date class is used

src/main/php/lang/reflect/ClassParser.class.php, src/test/php/net/xp_framework/unittest/reflection/ClassDetailsTest.class.php
This pull request makes it possible to use array notation inside attributes as follows:
```php
// Currently supported
#[Callback(eval: 'fn() => ...')]
class A { }
(new XPClass(A::class))->getAnnotation('callback'); // Closure{}
// Additionally supported
#[Callback(eval: ['fn() => ...'])]
class B { }
(new XPClass(B::class))->getAnnotation('callback'); // Closure{}
// Using named arguments
#[Callback(eval: ['function' => 'fn() => ...'])]
class C { }
(new XPClass(C::class))->getAnnotation('callback'); // ['function' => Closure{}]
```
Together with xp-framework/reflection#35, this is a prerequisite for extracting reflection code as proposed by xp-framework/rfc#338.
* * * 
⚠️ This does not offer full support because the XP Framework core annotation API is built around a *single-value* paradigm …
=> Support `eval` array notation inside attributes

src/main/php/util/UUID.class.php
> As an example a [GitHub Search](https://github.com/search?q=%22four+most+significant+bits+holds+version+number+4%22+language%3APHP&type=code&l=PHP) reveals that UUIDv4 implementations based on a [highly-voted Y2010 StackOverflow answer](https://stackoverflow.com/a/2040279) that uses [mt_rand](http://www.php.net/mt_rand)() are not uncommon, as per above, UUID collisions are expected after 80000 requests if nothing else uses randomness within the request.
> [...]
> To clean up the API and to guide developers to better alternatives, the global Mt19937 should be deprecated and then removed. The function-based API will then provide just the random_int() function which is the “secure by default” choice based on the CSPRNG
See https://wiki.php.net/rfc/deprecations_php_8_3#global_mersenne_twiste …
=> Use random_int() instead of mt_rand()

src/main/php/util/Random.class.php, src/test/php/net/xp_framework/unittest/util/RandomTest.class.php
> As an example a [GitHub Search](https://github.com/search?q=%22four+most+significant+bits+holds+version+number+4%22+language%3APHP&type=code&l=PHP) reveals that UUIDv4 implementations based on a [highly-voted Y2010 StackOverflow answer](https://stackoverflow.com/a/2040279) that uses [mt_rand](http://www.php.net/mt_rand)() are not uncommon, as per above, UUID collisions are expected after 80000 requests if nothing else uses randomness within the request.
> [...]
> To clean up the API and to guide developers to better alternatives, the global Mt19937 should be deprecated and then removed. The function-based API will then provide just the random_int() function which is the “secure by default” choice based on the CSPRNG
See https://wiki.php.net/rfc/deprecations_php_8_3#global_mersenne_twiste …
=> Deprecate Random::MTRAND

src/main/php/lang/reflect/ClassParser.class.php, src/test/php/lang/unittest/AnnotationParsingTest.class.php, src/test/php/lang/unittest/AttributeParsingTest.class.php, src/test/php/lang/unittest/ClassDetailsTest.class.php
This fixes a problem when using old and new reflection libraries in conjunction. This is due to the fact that both use `xp::$meta` for caching reasons, but fill it differently.
```php
<?php
use web\frontend\Handler;
#[Handler]
class Users {
}
```
Using the `lang.XPClass` annotation API will infer with the results returned by `lang.reflection.Type`:
```bash
$ xp -w 'return [...\lang\Reflection::type("Users")->annotations()]'
[web.frontend.Handler => lang.reflection.Annotation<web.frontend.Handler([])>]
$ xp -w '\lang\XPClass::forName("Users")->getAnnotations();
return [...\lang\Reflection::type("Users")->annotations()]'
[handler => lang.reflection.Annotation<handler([])>]
```
The `lang.XPClass` annotation API now also records the original annotation names, and `lang.reflection.Type` now …
=> Store original attribute names in DETAIL_TARGET_ANNO

src/main/php/io/streams/Buffer.class.php, src/test/php/io/unittest/BufferTest.class.php
Example:
```php
use io\streams\Buffer;
use lang\Environment;
$buffer= new Buffer(Environment::tempDir(), 1024);
// This will be written to memory as it's shorter than the threshold
$buffer->write('Slice #1');
// With this write, the buffer exceeds the threshold and is thus saved to a file
$buffer->write(str_repeat('*', 2048)); 
// Drain the buffer
while ($buffer->available()) {
$chunk= $buffer->read();
}
// Close the buffer, removing the file created by the second write
$buffer->close();
```
Inspired by https://github.com/xp-forge/web/issues/118
=> Implement a limited in-memory buffer with filesystem overflow

src/main/php/io/streams/StreamTransfer.class.php, src/test/php/io/unittest/StreamTransferTest.class.php
Example - inside a web handler:
```php
use io\streams\StreamTransfer;
$transfer= new StreamTransfer($file, $buffer);
yield from $transfer->transmit();
$transfer->close();
```
=> Add io.streams.StreamTransfer::transmit() which yields control after each chunk

src/main/php/util/Date.class.php, src/test/php/util/unittest/DateTest.class.php
```php
use util\Date;
new Date(1723897264);     // 12:21:04.000
new Date(1723897264.123); // 12:21:04.123
```
=> Support passing floating point numbers to constructor, setting microseconds

src/main/php/util/Date.class.php, src/test/php/util/unittest/DateTest.class.php
Following the paradigm: **Be liberal in what you accept**, all of these methods now accept `?string|util.TimeZone` instead of just `?TimeZone`:
=> Accept strings or util.TimeZone instances

src/main/php/lang/Environment.class.php, src/main/php/lang/Runtime.class.php, src/test/php/lang/unittest/EnvironmentTest.class.php
```php
$nproc= Environment::availableProcessors();
```
Inspired by .NET: https://learn.microsoft.com/en-us/dotnet/api/system.environment.processorcount?view=net-10.0
=> Add Environment::availableProcessors()

src/main/php/io/streams/SequenceInputStream.class.php, src/test/php/io/unittest/SequenceInputStreamTest.class.php
SequenceInputStream takes InputStream objects as sources. It reads from one source after the other in the given order. When it completes reading from the first InputStream, it automatically starts reading from the second. This process continues until it finishes reading from all the source streams.
```php
use io\streams\{SequenceInputStream, MemoryInputStream};
$in= new SequenceInputStream(new MemoryInputStream('One'), new MemoryInputStream('Two'));
$all= '';
while ($in->available()) {
$all.= $in->read();
}
$in->close();
// $all is now "OneTwo"
```
See https://docs.oracle.com/en/java/javase/24/docs/api/java.base/java/io/SequenceInputStream.html
=> Add SequenceInputStream

src/main/php/io/streams/MemoryInputStream.class.php, src/main/php/io/streams/MemoryOutputStream.class.php, src/test/php/io/unittest/MemoryInputStreamTest.class.php, src/test/php/io/unittest/MemoryOutputStreamTest.class.php
=> Consistency in memory I/O

src/main/php/io/streams/FileInputStream.class.php, src/main/php/io/streams/FileOutputStream.class.php, src/test/php/io/unittest/FileInputStreamTest.class.php, src/test/php/io/unittest/FileOutputStreamTest.class.php
Example:
```php
use io\streams\{FileInputStream, FileOutputStream};
$in= new FileInputStream('README.md');
$in->size(); // Size of README.md on disk
$out= new FileOutputStream('test.json');
$out->write(/* ... */);
$out->size(); // Size of file after writing
```
=> Add size() to both FileInputStream and FileOutputStream
