xp-framework/core

- .travis.yml
- src/main/php/lang/Runtime.class.php
See https://github.com/xp-framework/xp-runners/releases/tag/v5.2.0
> Upgrade to XP runners, v5.2.0

- src/main/php/lang.base.php
- src/test/php/net/xp_framework/unittest/core/UsesTest.class.php
This PR contains a fix for #48
> Fix uses not creating short aliases

- .travis.yml
- src/main/php/io/SpoolDirectory.class.php
- src/main/php/security/KeyPair.class.php
- src/main/php/security/sasl/DigestChallenge.class.php
- src/main/php/unittest/mock/arguments/Arg.class.php
- src/main/php/xp/install/GitHubArchive.class.php
Hey @kiesel this looks good - I'd like to merge it if that's OK for you:)
> Fix classrefs

- ChangeLog.md
- src/main/php/lang/XPClass.class.php
- src/test/php/net/xp_framework/unittest/reflection/PackageTest.class.php
- src/test/php/net/xp_framework/unittest/reflection/XPClassTest.class.php
- src/test/php/net/xp_framework/unittest/reflection/classes/UsingOne.class.php
This pull request adds `XPClass::isTrait()` and `XPClass::getTraits()` methods.
> Trait reflection

- .travis.yml
- README.md
- src/main/php/xp/unittest/Runner.class.php
- src/test/php/net/xp_framework/unittest/tests/UnittestRunnerTest.class.php
This is a dependency of xp-framework/xp-runners#24 and includes the following:
* Usage documentation for `unittest -w`
* Sets exitcode = 2 for argument errors
> Add handling for unittest -w

- src/main/php/lang.base.php
- src/test/php/net/xp_framework/unittest/core/UsesTest.class.php
Bugfix is required for XP6 to work.
> Backporting bugfix to v6.3.4: Fixes error when including class with import function via "uses"

- ChangeLog.md
- src/main/php/lang/FunctionType.class.php
- src/main/php/lang/XPClass.class.php
- src/main/php/lang/reflect/ClassParser.class.php
- src/main/php/lang/reflect/Field.class.php
- src/main/php/lang/reflect/Parameter.class.php
- src/main/php/lang/reflect/Routine.class.php
- src/test/php/net/xp_framework/unittest/reflection/ClassDetailsTest.class.php
- src/test/php/net/xp_framework/unittest/reflection/CompareTo.class.php
- src/test/php/net/xp_framework/unittest/reflection/FieldBasicsTest.class.php
- src/test/php/net/xp_framework/unittest/reflection/FieldsTest.class.php
- src/test/php/net/xp_framework/unittest/reflection/MethodBasicsTest.class.php
- src/test/php/net/xp_framework/unittest/reflection/MethodsTest.class.php
This pull request fixes the reflection API to honor traits:
> Reflection to honor traits

- src/main/php/lang.base.php
- src/main/php/lang/reflect/Field.class.php
- src/test/php/net/xp_framework/unittest/core/NewInstanceTest.class.php
- src/test/php/net/xp_framework/unittest/core/WithTest.class.php
- src/test/php/net/xp_framework/unittest/reflection/PrivateAccessibilityFixture.class.php
- src/test/php/net/xp_framework/unittest/reflection/ProtectedAccessibilityFixture.class.php
See https://github.com/xp-framework/rfc/issues/305:
> Return value returned by closure passed to with()

- src/main/php/io/Folder.class.php
- src/main/php/io/FolderEntries.class.php
- src/main/php/io/Path.class.php
- src/main/php/io/streams/OutputStreamWriter.class.php
- src/main/php/io/streams/StringWriter.class.php
- src/main/php/lang.base.php
- src/main/php/lang/FunctionType.class.php
- src/main/php/lang/System.class.php
- src/main/php/lang/XPClass.class.php
- src/main/php/util/AbstractDeferredInvokationHandler.class.php
- src/main/php/util/Locale.class.php
- src/main/php/util/TimeSpan.class.php
- src/main/php/util/cmd/Console.class.php
- src/test/php/net/xp_framework/unittest/core/ProcessTest.class.php
- src/test/php/net/xp_framework/unittest/core/generics/ListOf.class.php
- src/test/php/net/xp_framework/unittest/reflection/ClassFromUriTest.class.php
- src/test/php/net/xp_framework/unittest/util/DeferredInvokationHandlerTest.class.php
See
* [PHP RFC: Syntax for variadic functions](https://wiki.php.net/rfc/variadics)
* [PHP RFC: Argument Unpacking](https://wiki.php.net/rfc/argument_unpacking)
> Replace func_get_args() with variadics syntax

- src/main/php/unittest/mock/MockProxyBuilder.class.php
- src/test/php/net/xp_framework/unittest/tests/mock/MockProxyBuilderTest.class.php
This PR is a forward-port of PR #136 to branch *six*.
> Declare static initializer in a MockProxy

- ChangeLog.md
- src/main/php/lang.base.php
- src/main/php/lang/Type.class.php
- src/main/php/lang/XPClass.class.php
- src/main/php/lang/reflect/Routine.class.php
- src/test/php/net/xp_framework/unittest/core/CastingTest.class.php
- src/test/php/net/xp_framework/unittest/reflection/TypeTest.class.php
- src/test/php/net/xp_framework/unittest/reflection/XPClassTest.class.php
> Fix {Type,XPClass}::forName to support absolute type names

- ChangeLog.md
- src/main/php/lang/Process.class.php
- src/test/php/net/xp_framework/unittest/core/ProcessTest.class.php
```php
$p= new Process(...);
while ($p->running()) {
// Do something
}
```
> Implement new Process::running() method which tests if a process is running

- src/main/php/io/streams/TextReader.class.php
- src/main/php/io/streams/TextWriter.class.php
- src/main/php/lang/ArrayType.class.php
- src/main/php/lang/FunctionType.class.php
- src/main/php/lang/GenericTypes.class.php
- src/main/php/lang/MapType.class.php
- src/main/php/lang/Primitive.class.php
- src/main/php/lang/Type.class.php
- src/main/php/lang/TypeUnion.class.php
- src/main/php/lang/WildcardType.class.php
- src/main/php/lang/XPClass.class.php
- src/main/php/lang/reflect/Field.class.php
- src/main/php/lang/reflect/Method.class.php
- src/main/php/util/AbstractDeferredInvokationHandler.class.php
- src/main/php/util/Bytes.class.php
- src/main/php/util/Filters.class.php
- src/main/php/util/TimeSpan.class.php
- src/main/php/util/TimeZone.class.php
- src/test/php/net/xp_framework/unittest/core/ObjectTest.class.php
Prerequisite for xp-framework/rfc#323
> Replace xp::typeOf() with typeof()

- src/main/php/util/Secret.class.php
- src/test/php/net/xp_framework/unittest/util/SecretTest.class.php
```php
// Current
if ($password === $secret->reveal()) { ... }
// or, better:
if (hash_equals($secret->reveal(), $password)) { ... }
// New
if ($secret->equals($password)) { ... }
```
See also https://wiki.php.net/rfc/timing_attack
> Secret::equals()

- src/main/php/lang.base.php
- src/test/php/net/xp_framework/unittest/core/CastingTest.class.php
> Implement RFC 326: Cast and nullable types

- src/main/php/lang/FunctionType.class.php
- src/main/php/lang/MapType.class.php
- src/main/php/lang/Type.class.php
- src/main/php/lang/TypeUnion.class.php
- src/main/php/lang/WildcardType.class.php
- src/test/php/net/xp_framework/unittest/core/TypeUnionTest.class.php
> Fix type union parsing

- src/main/php/util/Secret.class.php
- src/test/config/unittest/util.ini
- src/test/php/net/xp_framework/unittest/util/SodiumSecretTest.class.php
> Implement PHP 7.2 sodium extension based encryption

- src/main/php/io/FileUtil.class.php
- src/main/php/io/Files.class.php
- src/test/config/unittest/io.ini
- src/test/php/net/xp_framework/unittest/io/FileUtilTest.class.php
- src/test/php/net/xp_framework/unittest/io/FilesTest.class.php
...as replacement for `io.FileUtil`.
> New Files class

- src/main/php/io/FileUtil.class.php
- src/main/php/io/Files.class.php
- src/test/config/unittest/io.ini
- src/test/php/net/xp_framework/unittest/io/FileUtilTest.class.php
- src/test/php/net/xp_framework/unittest/io/FilesTest.class.php
This pull request backports #217 for implementation in XP 9
> Backport new io.Files class replacing the ill-named FileUtil

- src/main/php/util/Dates.class.php
- src/test/config/unittest/date.ini
- src/test/php/net/xp_framework/unittest/util/DatesTest.class.php
This pull request backports #218 for implementation in XP 9
> Backport new util.Dates class superseding util.DateUtil

- src/main/php/util/Date.class.php
- src/test/php/net/xp_framework/unittest/util/DateTest.class.php
This pull request backports #219 for implementation in XP 9
> Backport adding util.Date::getMicroSeconds()

- src/main/php/lang/reflect/ClassParser.class.php
- src/test/php/net/xp_framework/unittest/reflection/ClassDetailsTest.class.php
This pull request backports #227 for implementation in XP 9
> Backport PHP 7.4 arrow functions in annotations

- src/main/php/lang/FunctionType.class.php
See https://github.com/xp-framework/core/issues/211#issuecomment-633213122
> Use ReflectionType API instead of deprecated isArray/isCallable on parameters

- src/main/php/util/Filter.class.php
- src/main/php/util/Filters.class.php
> Rewrite generics to new PHP 8 attribute syntax

- src/main/php/util/Secret.class.php
See https://github.com/openssl/openssl/blob/master/doc/man7/OSSL_PROVIDER-legacy.pod#symmetric-ciphers
> Use AES-128-CBC instead of DES

- src/main/php/util/Random.class.php
See https://wiki.php.net/rfc/rng_extension#prng_shootout
> Use Xoshiro256** (w/o seed) as the fastest engine for PHP 8.2+

- src/main/php/io/Folder.class.php
- src/test/php/io/unittest/FolderTest.class.php
Before, the `Folder::unlink()` method would recurse into symlinked directories and remove those, causing unwanted side effects if the symlink targets elements outside of the folder, or warnings about elements already being deleted if the targets are inside the folder.
> Fix removing directories with symlinks inside

- src/main/php/util/Properties.class.php
- src/test/php/util/unittest/AbstractPropertiesTest.class.php
- src/test/php/util/unittest/FileBasedPropertiesTest.class.php
- src/test/php/util/unittest/StreamBasedPropertiesTest.class.php
- src/test/php/util/unittest/StringBasedPropertiesTest.class.php
> Set default character set for property files to `utf-8`
